// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANQziik_xvN-16yCCyuwiBcVDPg8QLMJ0',
    appId: '1:173334715793:web:b3513999852adb7cbf4e30',
    messagingSenderId: '173334715793',
    projectId: 'nabaai-b1998',
    authDomain: 'nabaai-b1998.firebaseapp.com',
    storageBucket: 'nabaai-b1998.firebasestorage.app',
    measurementId: 'G-F12QQ680HN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKmGUrr07DmgjYIkzysLOUzAbq0Cp2iYM',
    appId: '1:173334715793:android:c00e09cb8d3509c8bf4e30',
    messagingSenderId: '173334715793',
    projectId: 'nabaai-b1998',
    storageBucket: 'nabaai-b1998.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC1Pe_kghEOjSEjPv65fHvV6JJf6rggZY',
    appId: '1:173334715793:ios:b551cb5129c3a4f5bf4e30',
    messagingSenderId: '173334715793',
    projectId: 'nabaai-b1998',
    storageBucket: 'nabaai-b1998.firebasestorage.app',
    iosBundleId: 'com.example.progect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwcDmdzSBQmEBxc-PNKyQ1vNWcbPwPAls',
    appId: '1:173334715793:ios:b551cb5129c3a4f5bf4e30',
    messagingSenderId: '173334715793',
    projectId: 'nabaai-b1998',
    storageBucket: 'nabaai-b1998.firebasestorage.app',
    iosBundleId: 'com.example.progect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANQziik_xvN-16yCCyuwiBcVDPg8QLMJ0',
    appId: '1:173334715793:web:47e348fa6df078f7bf4e30',
    messagingSenderId: '173334715793',
    projectId: 'nabaai-b1998',
    authDomain: 'nabaai-b1998.firebaseapp.com',
    storageBucket: 'nabaai-b1998.firebasestorage.app',
    measurementId: 'G-QRCXNP0084',
  );
}
